### PR TITLE
Add backpressure support for non single value database queries

### PR DESCRIPTION
**Pull request by OrdonTeam**

### CODE REVIEW

**Comment by nmoskalenko** [comment]
@OrdonTeam , hm..
Could you please list the reasons why backpressure support should be inside the library?
In general, I don't want to make any decisions for user inside the lib. Personally I'm setting up backpressure rules on app layer.

**Comment by OrdonTeam** [comment]
Hmm, I didn't think that way..
I always assume that observable handle backpressure itself.

If you want to change backpressure rules you still can. Correct me if I'm wrong but I think that library users who already add backpressure support (ex. drop rule), they don't have to change theirs code anyway.

It is general rule to for me to use `fromAsync` for converting callbacks to observables.

**Comment by nmoskalenko** [comment]
I've never used fromAsync before. Yeah, may be providing default backpressure option does make sense.
Anyway, thanks for this PR, I'll play with it a little bit to understand how it works and, if users would not be limited, would merge it!

**Comment by renanferrari** [comment]
Please note that `Observable.fromAsync()`'s name is going to [change soon](https://github.com/ReactiveX/RxJava/pull/4442), in RxJava 1.2.0.

**Comment by alexandru** [comment]
Guys, FYI, buffering everything incoming in an unbounded buffer is not back-pressuring anything.

Which is what you're doing when specifying `AsyncEmitter.BackpressureMode.BUFFER`.

**Pull request closed without merging**
